// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // fallback : la connexion réelle passe par un driver adapter
    // (@libsql/client / better-sqlite3) dans lib/prisma.ts, pas par
    // cette URL. On évite juste que `prisma generate` plante si
    // DATABASE_URL n'est pas définie (ex: build Vercel).
    url: process.env.DATABASE_URL || "file:./dev.db",
  },
});
